---
title: "White Noise and Random Walks: Part 1 -- Handout"
subtitle: "Chapter 4: Lesson 1"
format: html
editor: source
sidebar: false
---

```{r}
#| include: false
source("common_functions.R")
```

```{=html}
<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
 
 function openTab(evt, tabName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
 }    
</script>
```

### Coin Toss Experiment

::: {.callout-tip appearance="minimal"}


1.  Start the time series at $x_0 = 0$.
2.  Toss a coin. 
    -   If the coin shows heads, then $x_t = x_{t-1}+1$
    -   If the coin shows tails, then $x_t = x_{t-1}-1$
3.  Plot the new point on the time plot.
4.  Complete steps 2 and 3 a total of $n=60$ times.


```{r}
#| echo: false

set.seed(7)

df <- data.frame(x=0:60) |>
  mutate(w = ifelse(row_number() == 1, 0, sample(c(-1,1), size = 60, replace = TRUE))) |>
  mutate(y = cumsum(w))
# df  
# 
df2 <- expand_grid(x = 0:60, y = -20:20)

df_point <- data.frame(x = 0, y = 0)

ggplot(data=df2, aes(x=x, y=y)) +
  # geom_point(data = df2, aes(x=x, y=y), size = 0.01) +
  # geom_line(data = df, aes(x=x, y=y)) +
  # geom_point(data = df, aes(x=x, y=y), size = 0.5) +
  geom_point(data = df_point, aes(x=x, y=y), size = 1.5) +
  scale_x_continuous(limits = c(0,60),
                     breaks = seq(0, 60, by = 5),
                     minor_breaks = seq(0, 60, 1)) +
  scale_y_continuous(limits = c(-20,20),
                     breaks = seq(-20, 20, by = 5),
                     minor_breaks = seq(-20, 20, 1)) +
  labs(
      x = "Toss Number",
      y = "Value",
      title = "Cumulative Results of Coin Tosses"
  ) +
  theme_minimal() +
  theme(
    panel.grid.major = element_line(colour = "black"),
    # panel.grid.minor = element_line(colour = "black", linetype = "dotted", linewidth = 0.5)
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```


:::
