---
title: "Bass Model"
subtitle: "Chapter 3: Lesson 2"
format: html
editor: source
sidebar: false
---

```{r}
#| include: false
source("common_functions.R")
```

```{=html}
<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
 
 function openTab(evt, tabName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
 }    
</script>
```


## Learning Outcomes

<details>
<summary>Implement the Bass model</summary>
    -   Describe the types of times series for which the Bass model is appropriate
    -   Apply the Bass model to a time series
</details>


## Preparation

-   Read Section 3.3


## Learning Journal Exchange (10 mins)

-   Review another student's journal

-   What would you add to your learning journal after reading another student's?

-   What would you recommend the other student add to their learning journal?

-   Sign the Learning Journal review sheet for your peer


## Class Activity: Interpreting the Bass Model (30 mins)

The Bass formula, given as Equation (3.6) in the textbook is:

$$
  N_{t+1} = N_t + p(m-N_t) + q N_t (m-N_t) / m
$$

-   What situation is the Bass formula designed to model?
-   What do the following terms represent?
    -   $N_t$
    -   $N_{t+1} - N_t$ 
    -   $m$
    -   $m-N_t$
    -   $\dfrac{N_{t+1} - N_t}{m-N_t}$
    -   $p$
    -   $\dfrac{q N_t}{m}$
-   Rearrange Equation (3.6) to find an expression that equals $\dfrac{N_{t+1} - N_t}{m-N_t}$. 
-   The book states that "The rationale for the model is that initial sales will be to people who are interested in the novelty of the product, whereas later sales will be to people who are drawn to the product after seeing their friends and acquaintances use it." How does the expression that results from rearranging Equation (3.6) accord with this quote?

The explicit solution to the Bass formula is given in Equation (3.7) of the textbook:

$$
  N_t = m \dfrac{
                    1 - e^{-(p+q)t}
                }{
                    1 + \frac{q}{p} e^{-(p+q)t}
                }
$$

-   Using any tool (i.e., R, Mathematica, Desmos, graphing calculator), plot Equation (3.7) for various choices of $p$ and $q$.
-   Verify that Equation (3.7) is the solution to the Bass formula by doing the following.
    -   Using Equation (3.7), write down an expression for $N_{t+1}$.
    -   Substitute the value for $N_t$ given in Equation (3.7) into the right-hand side of Equation (3.6). Simplify the resulting expression to show that it is equal to $N_{t+1}$.

## Class Activity: XXXXXXX (15 mins)



## Recap (5 min)

Working with your partner, prepare to explain the following concepts to the class:



<a href="javascript:showhide('Solutions')"
style="font-size:.8em;">Class Activity</a>

::: {#Solutions style="display:none;"}

Solutions to Class Activity

\begin{align*}
  N_{t+1} 
    &= m \dfrac{ 1 - e^{-(p+q)(t+1)} }{ 1 + \frac{q}{p} e^{-(p+q)(t+1)} } \\
    &= m \dfrac{ 1 - e^{-(p+q)t}e^{-(p+q)} }{ 1 + \frac{q}{p} e^{-(p+q)t}e^{-(p+q)} } 
\end{align*}
\begin{align*}
  N_{t+1} 
    &= N_t + p(m-N_t) + \frac{q N_t}{m} (m-N_t) \\
    &= \left[ m \dfrac{ 1 - e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right] + p\left(m-\left[ m \dfrac{ 1 - e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right]\right) + \frac{q N_t}{m} \left(m-\left[ m \dfrac{ 1 - e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right]\right)  
\end{align*}

Let's simplify a common term:

\begin{align*}
  \left(m-\left[ m \dfrac{ 1 - e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right]\right)
    &= m\left(1-\left[ \dfrac{ 1 - e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right]\right) \\
    &= m\left(\dfrac{ \left[ 1 + \frac{q}{p} e^{-(p+q)t} \right]-\left[  1 - e^{-(p+q)t} \right] }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right) \\
    &= m\left(\dfrac{ \frac{q}{p} e^{-(p+q)t} + e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right) 
\end{align*}

Note that

\begin{align*}
  \frac{q N_t}{m} (m-N_t)
    &= \frac{q N_t}{m} 
        \cdot
        m\left(\dfrac{ \frac{q}{p} e^{-(p+q)t} + e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right) \\
    &= q 
        \cdot
          m \dfrac{ 1 - e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} }
        \cdot
          \left(\dfrac{ \frac{q}{p} e^{-(p+q)t} + e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right) \\
\end{align*}

Putting it all together, we have:

\begin{align*}
  N_{t+1} 
    &= N_t + p(m-N_t) + \frac{q N_t}{m} (m-N_t)\\
    &= \left[ m \dfrac{ 1 - e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right] 
        + p\left(m-\left[ m \dfrac{ 1 - e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right]\right) 
        + \frac{q N_t}{m} \left(m-\left[ m \dfrac{ 1 - e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right]\right)  \\
    &= \left[ m \dfrac{ 1 - e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right] 
        + p \cdot m\left(\dfrac{ \frac{q}{p} e^{-(p+q)t} + e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right) 
        + \frac{q N_t}{m} \cdot m\left(\dfrac{ \frac{q}{p} e^{-(p+q)t} + e^{-(p+q)t} }{ 1 + \frac{q}{p} e^{-(p+q)t} } \right) \\
    &= 
      \frac{
        \left[ m \left( 1 - e^{-(p+q)t} \right) \right] 
          + p \cdot m\left( \frac{q}{p} e^{-(p+q)t} + e^{-(p+q)t} \right) 
          + \frac{q N_t}{m} \cdot m\left( \frac{q}{p} e^{-(p+q)t} + e^{-(p+q)t} \right) 
      }{ 1 + \frac{q}{p} e^{-(p+q)t} }\\
    &= 
      \frac{
         m - m e^{-(p+q)t} 
          +  mq e^{-(p+q)t} + mp e^{-(p+q)t} 
          + q N_t \left( \frac{q}{p} e^{-(p+q)t} + e^{-(p+q)t} \right) 
      }{ 1 + \frac{q}{p} e^{-(p+q)t} }\\
    &= 
\end{align*}

\begin{align*}
~\\
\end{align*}
:::