---
title: "Resources"
listing:
  contents: resources
  fields: [image, title]
  type: grid
  categories: true
---

::: supplement
::: supplement-header
**Tidyverse Conversion**
:::

::: supplement-container
### [Supplement to Introductory Time Series with R](https://byuistats.github.io/timeseries_supplement/)
:::
:::

::: {.callout-note title="Common Packages" icon="false"}
```{r message=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, 
               tsibble, fable,
               feasts, tsibbledata,
               fable.prophet,
               patchwork,
               lubridate, 
               rio 
)
```

Full list of libraries used throughout the lessons
```{r message=FALSE}
pacman::p_load(MASS, # MVNorm, loaded before tidyverse so it doesn't overwrite dplyr::select()
               tidyverse, kableExtra,
               tsibble, fable,
               feasts, tsibbledata,
               fable.prophet,
               patchwork,
               ggthemes,
               see,   # okabeito color scheme
               ggokabeito, # colorblind palette
               stringr, # string manipulation
               lubridate, # date manipulation
               rio, # for easy i/o
               tidyquant,
               gt, # grammar of tables, for LaTeX in tables
               quarto, # For LaTeX mode results = 'asis'
               plotly # For interactive figures
)
```
:::
