---
title: "Sample Statistics and Correlation"
subtitle: "Chapter 2"
format: html
editor: source
sidebar: false
number-sections: true
number-depth: 3  # Numbers only ## and ### headings
number-offset: 1
---

# Chapter 2

(I known this looks funky, its a quarto numbering quirk, I assume the when we host through the school they will get around this with something more versatile.)

## Motivate the chapter. Why does it matter?

### Connect this with Ch1.1

## Differentiate population and sample properties and statistics

### Define population and samples

### Illustrate population and samples using pdf and histogram

## Contrast parameters and statistics, estimators and estimates

## Calculate a sample arithmetic mean

### Define expected value and sample mean

### Explain the intuition of sample mean using a histogram

## Calculate a sample standard deviation

### Define population and sample variance standard deviation

### Explain the intuition behind the sample standard deviation using a histogram

### Explain a box and whiskers plot.

## Calculate sample covariance and correlation coefficient.

### Define covariance and sample covariance

### Explain the intuition of covariance using a scatter plot

### Define the correlation and sample correlation coefficient.

### Interpret an estimate of sample correlation coefficient.

## Calculate a sample autocorrelation

### Define population and sample autocorrelation

### Explain the intuition of sample autocorrelation using a scatter plot

### Interpret an estimate of sample autocorrelation at different lags

### Define a correlogram

### Conduct hypothesis testing using a correlogram
