---
title: "Chapter 1: Lesson 1"
format: html
editor: visual
---

```{r}
#| include: false
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggokabeito, kableExtra)
palette("okabeito")
okabeito_colors_list <- c(
    `orange` = "#E69F00",
    `light blue` = "#56B4E9",
    `green` = "#009E73",
    `yellow` = "#F0E442",
    `blue` = "#0072B2",
    `red` = "#D55E00",
    `purple` = "#CC79A7",
    `grey` = "#999999",
    `black` = "#000000",
    `sky blue` = "#56B4E9",
    `bluish green` = "#009E73",
    `vermillion` = "#D55E00",
    `reddish purple` = "#CC79A7",
    `dark yellow` = "#F5C710",
    `amber` = "#F5C710"
)


round_df <- function(df, digits) {
  nums <- vapply(df, is.numeric, FUN.VALUE = logical(1))
  df[,nums] <- round(df[,nums], digits = digits)
  (df)
}
```

# Chapter 1: Lesson 1

## Objectives

-   Introduce the course structure and syllabus

-   Get to know each other

-   Describe key concepts in time series analysis

-   Explore an example time series interactively

## Introduction to the course structure and Canvas (30 min)

```         
-   Introduction of teacher(s)

-   Introduction of students

-   Syllabus

-   Textbook

    -   Cowpertwait, P. S. P., & Metcalfe, A. V. (2009). *Introductory Time Series with R*. Springer. ISBN 978-0-387-88697-8; e-ISBN 978-0-387-88698-5; DOI 10.1007/978-0-387-88698-5.

-   Supplement to the Textbook

    -   Modern R code

-   Grading Categories

    -   Attendance / Participation (5%)

    -   Reading Journal (10%)

    -   Homework (35%)

    -   Projects (20%)

    -   Exams (30%)

-   Grades: 93% = A

-   Daily Assignments

    -   Reading

    -   Homework

-   Reading Journals

    -   Document your learning

    -   Include all of the following from the assigned reading: vocabulary terms, nomenclature, models, important concepts, and your questions

    -   Review another student's learning journal at the beginning of class

-   Calendar

-   Time Series Notebook (Quarto) for in-class activities

-   Team structure for class activities

    -   Random assignment, frequent changes, partner with each student in the class

-   Lesson cadence

    -   Read section(s) from the textbook

    -   Reading Journal

    -   Class Activities

    -   Homework

-   Assessment Structure

    -   Homework, Projects, Exams
```

## Class Activity: Introduction to Time Series Data (15 mins)

-   What is time series data?

-   Examples of time series data

-   Why ordinary regression fails -- correlated error terms

-   Define "time series" (e.g. observations collected sequentially over time)

-   Examples of time series from different domains:

    -   Daily credit card balance

    -   Daily closing stock prices

    -   Monthly sales figures

    -   Yearly global temperature measurements

    -   Secondly wave heights in an ocean buoy

    -   Weekly unemployment rates

    -   Quarterly GDP estimates

-   Importance of context and subject matter knowledge

-   Role of models (explanation, prediction, simulation)

-   Introduce key features: trend, seasonality, autocorrelation

::: callout-caution
Please add an R chunk to illustrate the decomposition of a time series. For example, the Google Trends data for a search for one of these words:

-   Love

-   Marriage

-   Morals

-   Jesus

-   Latter-day Saints (Start at Jan 1, 2010; Note the breakpoint in October 2018, when President Nelson gave the talk, "The Correct Name of the Church.")

-   Depression

-   Virtue

-   General Conference
:::

-   Vocabulary terms (Identify each in the example above):

    -   Time series analysis

    -   Time series

    -   Sampling interval

    -   Serial dependence or autocorrelation

    -   Time series trend

    -   Seasonal variation

    -   Cycle

    -   Deterministic vs. Stochastic

::: callout-caution
This needs to be shifted to another lesson. There is not enough time here. \## Random walks (5-10 mins)

```         
-   Definition of a random walk

-   Example: tossing a coin and moving left or right one integer on a number line
-   Please add simulation of random walk here
```
:::

## Recap (5 mins)

-   Review objectives and key concepts

-   Clarify questions on course or time series data

## Preparation for the next class meeting

-   Update R and RStudio

-   Access the Time Series Notebook (Quarto file)

-   Purchase the textbook

-   Read Chapter 1

-   Create a reading journal

-   Prepare to share your reading journal with another student in the next class meeting
