---
title: "Chapter 1: Lesson 3"
subtitle: "Averages for Time Series"
format: html
editor: source
---


## Learning Outcomes

<details>
<summary>Decompose time series into trends, seasonal variation, and residuals</summary>
    -   Describe additive decomposition
    -   Describe multiplicative decomposition
    -   Define moving average of a time series
    -   Estimate trend component using moving averages
    -   Differentiate between deterministic and stochastic trends
</details>
<details>
<summary>Use R to describe key features of time series data</summary>
    -   Import CSV data and convert to tsibble format
</details>
<summary>Understand the purpose and limitations of forecasting</summary>
    -   Define forecasting
    -   Differentiate causation from correlation
</details>
<details>
<summary>Explain the key theoretical concepts of time series decomposition</summary>
    -   Define smoothing
    -   Explain a centered moving average
    -   Explain the differences in additive vs multiplicative estimators of seasonal variation
</details>



## Preparation

-   Read Sections 1.5.1-1.5.3


## Learning Journal Exchange (10 mins)

-   Review another student's journal
-   What would you add to your learning journal after reading your partner's?
-   What would you recommend your partner add to their learning journal?
-   Sign the Learning Journal review sheet for your peer


## Random walks (5-10 mins)

```         
-   Definition of a random walk
-   Example: tossing a coin and moving left or right one integer on a number line
```

::: callout-solution
Please add simulation of random walk here
:::

## When to use additive vs. multiplicative decomposition (5 min)

-   Additive: Constant variance
-   Multiplicative: Variance grows with the value of the time series

## Decomposition of a Time Series in Excel (40 min)

::: callout-caution
Provide 36 months worth of data

Students will compute a mean by hand

Students will compute (some values of) the additive decomposition by hand (Partial table given)

-   Students will compute some values of the centered moving average by hand
-   Students will compute some values of the monthly additive effect by hand
-   Students will compute some values of the seasonally adjusted series by hand
-   Students will plot some values of the decomposed time series by hand (Plot given)
:::








::: callout-warning
Watch out for the difference between these multiplicative models:

Textbook model: $$ x_t = m_t \cdot s_t + z_t $$

R's model: $$ x_t = m_t \cdot s_t \cdot z_t $$
:::




## Recap (5 mins)

```         
-   Review objectives and key concepts
-   Clarify questions on course or time series data
```
