---
title: "Chapter 1: Lesson 4"
subtitle: "Decomposition of Time Series"
format: html
editor: source
---


## Learning Outcomes

-   

## Preparation

-   Read Sections 1.5.4-1.5.5 and 1.6


## Learning Journal Exchange (10 mins)

-   Review another student's journal
-   What would you add to your learning journal after reading another student's?
-   What would you recommend the other student add to their learning journal?
-   Sign the Learning Journal review sheet for your peer


## Random walks (5-10 mins)

```         
-   Definition of a random walk
-   Example: tossing a coin and moving left or right one integer on a number line
```

::: callout-solution
Please add simulation of random walk here
:::

## When to use additive vs. multiplicative decomposition (5 min)

-   Additive: Constant variance
-   Multiplicative: Variance grows with the value of the time series

## Decomposition of a Time Series in Excel (40 min)

::: callout-caution
Provide 36 months worth of data

Students will compute a mean by hand

Students will compute (some values of) the additive decomposition by hand (Partial table given)

-   Students will compute some values of the centered moving average by hand
-   Students will compute some values of the monthly additive effect by hand
-   Students will compute some values of the seasonally adjusted series by hand
-   Students will plot some values of the decomposed time series by hand (Plot given)
:::

## Recap (5 mins)

```         
-   Review objectives and key concepts
-   Clarify questions on course or time series data
```
