---
title: "Chapter 3: Lesson 3"
subtitle: "Exponential Smoothing & the Holt-Winters Method"
format: html
editor: source
---

```{r}
#| include: false
source("../common_functions.R")
```


## Learning Outcomes

<details>    
<summary>Implement simple exponential smoothing to estimate local mean levels</summary>
    -   Explain forecasting by extrapolation 
    -   State the assumptions of exponential smoothing
    -   Define EWMA
    -   State the exponential smoothing forecasting equation
    -   State the EWMA in geometric series form (terms of x_t only Eq 3.18)
    -   Explain the EWMA intuitively in three different ways
    -   Define the one-step-ahead prediction error (1PE)
    -   State the SS1PE used to estimate the smoothing parameter of a EWMA
    -   Remember under which conditions the EWMA smoothing parameter is optimally 1/n
</details>


## Preparation

-   Read Section 3.4.1


## Learning Journal Exchange (10 mins)

-   Review another student's journal

-   What would you add to your learning journal after reading another student's?

-   What would you recommend the other student add to their learning journal?

-   Sign the Learning Journal review sheet for your peer


## Class Activity: XXXXXXX (15 mins)



## Recap (5 min)

Working with your partner, prepare to explain the following concepts to the class:

