<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BYU-Idaho Time Series - Transformations and Non-Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter_5_lesson_5.html" rel="next">
<link href="./chapter_5_lesson_3.html" rel="prev">
<link href="./images/TSFavicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./images/TSfavicon_inv.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BYU-Idaho Time Series</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Table of Contents</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resource_blog.html" rel="" target="">
 <span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-chapter-1" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Chapter 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-chapter-1">    
        <li class="dropdown-header">Overview</li>
        <li>
    <a class="dropdown-item" href="./chapter_1.html" rel="" target="">
 <span class="dropdown-text">Lessons &amp; Homework</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 1</li>
        <li>
    <a class="dropdown-item" href="./chapter_1_lesson_1.html" rel="" target="">
 <span class="dropdown-text">Course Introduction</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 2</li>
        <li>
    <a class="dropdown-item" href="./chapter_1_lesson_2.html" rel="" target="">
 <span class="dropdown-text">Plots Trends, and Seasonal Variation</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 3</li>
        <li>
    <a class="dropdown-item" href="./chapter_1_lesson_3.html" rel="" target="">
 <span class="dropdown-text">Averages for Time Series</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 4</li>
        <li>
    <a class="dropdown-item" href="./chapter_1_lesson_4.html" rel="" target="">
 <span class="dropdown-text">Additive Models</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 5</li>
        <li>
    <a class="dropdown-item" href="./chapter_1_lesson_5.html" rel="" target="">
 <span class="dropdown-text">Multiplicative Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-chapter-2" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Chapter 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-chapter-2">    
        <li class="dropdown-header">Overview</li>
        <li>
    <a class="dropdown-item" href="./chapter_2.html" rel="" target="">
 <span class="dropdown-text">Lessons &amp; Homework</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 1</li>
        <li>
    <a class="dropdown-item" href="./chapter_2_lesson_1.html" rel="" target="">
 <span class="dropdown-text">Covariance and Correlation</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 2</li>
        <li>
    <a class="dropdown-item" href="./chapter_2_lesson_2.html" rel="" target="">
 <span class="dropdown-text">Autocorrelation Concepts</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 3</li>
        <li>
    <a class="dropdown-item" href="./chapter_2_lesson_3.html" rel="" target="">
 <span class="dropdown-text">Exploration of Autocorrelation Concepts</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-chapter-3" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Chapter 3</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-chapter-3">    
        <li class="dropdown-header">Overview</li>
        <li>
    <a class="dropdown-item" href="./chapter_3.html" rel="" target="">
 <span class="dropdown-text">Lessons &amp; Homework</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 1</li>
        <li>
    <a class="dropdown-item" href="./chapter_3_lesson_1.html" rel="" target="">
 <span class="dropdown-text">Leading Variables and Associated Variables</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 2</li>
        <li>
    <a class="dropdown-item" href="./chapter_3_lesson_2.html" rel="" target="">
 <span class="dropdown-text">Exponential Smoothing (EWMA)</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 3</li>
        <li>
    <a class="dropdown-item" href="./chapter_3_lesson_3.html" rel="" target="">
 <span class="dropdown-text">Holt-Winters Method (Additive Models) - Part 1</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 4</li>
        <li>
    <a class="dropdown-item" href="./chapter_3_lesson_4.html" rel="" target="">
 <span class="dropdown-text">Holt-Winters Method (Additive Models) - Part 2</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 5</li>
        <li>
    <a class="dropdown-item" href="./chapter_3_lesson_5.html" rel="" target="">
 <span class="dropdown-text">Holt-Winters Method (Multiplicative Models)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-chapter-4" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Chapter 4</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-chapter-4">    
        <li class="dropdown-header">Overview</li>
        <li>
    <a class="dropdown-item" href="./chapter_4.html" rel="" target="">
 <span class="dropdown-text">Lessons &amp; Homework</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 1</li>
        <li>
    <a class="dropdown-item" href="./chapter_4_lesson_1.html" rel="" target="">
 <span class="dropdown-text">White Noise and Random Walks - Part 1</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 2</li>
        <li>
    <a class="dropdown-item" href="./chapter_4_lesson_2.html" rel="" target="">
 <span class="dropdown-text">White Noise and Random Walks - Part 2</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 3</li>
        <li>
    <a class="dropdown-item" href="./chapter_4_lesson_3.html" rel="" target="">
 <span class="dropdown-text">Autoregressive Models</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 4</li>
        <li>
    <a class="dropdown-item" href="./chapter_4_lesson_4.html" rel="" target="">
 <span class="dropdown-text">Fitted Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-chapter-5" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Chapter 5</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-chapter-5">    
        <li class="dropdown-header">Overview</li>
        <li>
    <a class="dropdown-item" href="./chapter_5.html" rel="" target="">
 <span class="dropdown-text">Lessons &amp; Homework</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 1</li>
        <li>
    <a class="dropdown-item" href="./chapter_5_lesson_1.html" rel="" target="">
 <span class="dropdown-text">Linear Models, GLS, and Seasonal Indicator Variables</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 2</li>
        <li>
    <a class="dropdown-item" href="./chapter_5_lesson_2.html" rel="" target="">
 <span class="dropdown-text">Harmonic Seasonal Variables - Part 1</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 3</li>
        <li>
    <a class="dropdown-item" href="./chapter_5_lesson_3.html" rel="" target="">
 <span class="dropdown-text">Harmonic Seasonal Variables - Part 2</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 4</li>
        <li>
    <a class="dropdown-item" href="./chapter_5_lesson_4.html" rel="" target="">
 <span class="dropdown-text">Transformations and Non-Linear Models</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Lesson 5</li>
        <li>
    <a class="dropdown-item" href="./chapter_5_lesson_5.html" rel="" target="">
 <span class="dropdown-text">Forecasting, Inverse Transformation, and Bias Correction</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes">Learning Outcomes</a></li>
  <li><a href="#preparation" id="toc-preparation" class="nav-link" data-scroll-target="#preparation">Preparation</a></li>
  <li><a href="#learning-journal-exchange-10-min" id="toc-learning-journal-exchange-10-min" class="nav-link" data-scroll-target="#learning-journal-exchange-10-min">Learning Journal Exchange (10 min)</a></li>
  <li><a href="#class-activity-simulate-an-exponential-trend-with-a-seasonal-component-15-min" id="toc-class-activity-simulate-an-exponential-trend-with-a-seasonal-component-15-min" class="nav-link" data-scroll-target="#class-activity-simulate-an-exponential-trend-with-a-seasonal-component-15-min">Class Activity: Simulate an Exponential Trend with a Seasonal Component (15 min)</a></li>
  <li><a href="#small-group-activity-retail-sales-20-min" id="toc-small-group-activity-retail-sales-20-min" class="nav-link" data-scroll-target="#small-group-activity-retail-sales-20-min">Small-Group Activity: Retail Sales (20 min)</a></li>
  <li><a href="#class-activity-simulated-non-linear-series-10-min" id="toc-class-activity-simulated-non-linear-series-10-min" class="nav-link" data-scroll-target="#class-activity-simulated-non-linear-series-10-min">Class Activity: Simulated Non-Linear Series (10 min)</a></li>
  <li><a href="#homework-preview-5-min" id="toc-homework-preview-5-min" class="nav-link" data-scroll-target="#homework-preview-5-min">Homework Preview (5 min)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Transformations and Non-Linear Models</h1>
<p class="subtitle lead">Chapter 5: Lesson 4</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
 
 function openTab(evt, tabName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
 }    
</script>
<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning Outcomes</h2>
<details>
<summary>
Apply logarithmic transformations to time series
</summary>
<ul>
<li>Explain when to use a log-transformation</li>
<li>Estimate a harmonic seasonal model using GLS with a log-transformed series</li>
<li>Explain how to use logarithms to linearize certain non-linear trends</li>
</ul>
</details>
<details>
<summary>
Apply non-linear models to time series
</summary>
<ul>
<li>Explain when to use non-linear models</li>
<li>Simulate a time series with an exponential trend</li>
<li>Fit a time series model with an exponential trend</li>
</ul>
</details>
<!--
From Daniel: 

5.  Regression
5.1.    Purpose
•   Explain the different treatment of stochastic and deterministic trends on forecasting
5.2.    Linear Models
5.2.1.  Definition
•   Define a linear time series model
•   State the exogeneity assumption: the expected value of the error terms is zero
5.2.2.  Stationarity
•   Transform a non-stationary linear to a stationary process using differencing
•   State how to remove a polynomial trend of order m
5.2.3.  Simulation
•   Simulate a time series with a linear time trend and a AR(p) error
5.3.    Fitted Models
5.3.1.  Model fitted to simulated data
•   Estimate a linear model for a simulated time series with linear time trend and AR(p) error
5.3.2.  Model fitted to the temperature series
•   Use acf and pacf to test for autocorrelation bias in standard errors
•   Explain intuitively why autocorrelated error terms leads to bias of estimated standard errors
5.3.3.  Autocorrelation and the estimation and sample statistics*
5.4.    Generalized Least Squares
5.4.1.  GLS fit to simulated series
•   Estimate a linear model using the GLS algorithm
•   Compare GLS and OLS standard error estimates to evaluate autocorrelation bias
•   Explain the process to estimate the autocorrelation input for the GLS algorithm
5.4.2.  Confidence interval for the trend in the temperature series
5.5.    Linear Models with seasonal variables
5.5.1.  Introduction
5.5.2.  Additive seasonal indicator variables
•   State the additive model with seasonal indicator variables (eq 5.7 & 5.8)
•   Create seasonal indicator variables using the factor() and cycle() functions
5.5.3.  Example seasonal model for the temperature series
•   Estimate a seasonal indicator model using GLS
•   Forecast using a GLS fitted seasonal indicator model
5.6.    Harmonic Seasonal Models
•   Motivate the use of the harmonic seasonal model
•   State the additive model with harmonic seasonal component
•   Explain the use of higher frequency harmonic components to model seasonal variation
5.6.2.  Simulation
•   Simulate a time series with harmonic seasonal components
5.6.3.  Fit to the simulated series
•   Use a t-ratio to decide the statistical significance of harmonic coefficient estimates
•   Use AIC to aid in model selection
•   Illustrate the limitations of AIC
5.6.4.  Harmonic model fitted to the temperature series
•   Fit the additive model with harmonic seasonal component to real-world data
•   Evaluate residuals using a correlogram and partial correlogram to ensure they meet the exogeneity assumption
•   Model residuals using an AR(p) model to meet the exogeneity assumption
5.7.    Logarithmic transformations
5.7.1.  Introduction
•   Explain when to use a log-transformation
5.7.2.  Example using the air passenger series
•   Estimate a harmonic seasonal model using GLS with a log-transformed series
5.8.    Non-linear model
5.8.1.  Introduction
•   Explain when to use non-linear models
•   Explain how to use logarithms to transform non-linear into linear functions
5.8.2.  Example of a simulated and fitted non-linear series
•   Simulate a time series with a non-linear exponential trend
•   Fit a non-linear exponential trend.
5.9.    Forecasting from regression
5.9.1.  Introduction
5.9.2.  Prediction in R
•   Use a log-transformation to multiplicative time series
•   Forecast using the inverse-transform and bias correction of a log-transformed model
5.10.   Inverse Transform and Bias Correction
5.10.1. Log-normal residual errors
•   State the bias correction procedure for log-transform estimates (eq 5.19)
5.10.2. Empirical correction factor for forecasting means
•   Explain when to use the bias correction factor
5.10.3. Example using the air passenger data
•   Use the bias correction factor for a log-transform model

-->
</section>
<section id="preparation" class="level2">
<h2 class="anchored" data-anchor-id="preparation">Preparation</h2>
<ul>
<li>Read Sections 5.7-5.8</li>
</ul>
</section>
<section id="learning-journal-exchange-10-min" class="level2">
<h2 class="anchored" data-anchor-id="learning-journal-exchange-10-min">Learning Journal Exchange (10 min)</h2>
<ul>
<li><p>Review another student’s journal</p></li>
<li><p>What would you add to your learning journal after reading another student’s?</p></li>
<li><p>What would you recommend the other student add to their learning journal?</p></li>
<li><p>Sign the Learning Journal review sheet for your peer</p></li>
</ul>
<!-- {{< include _packages.qmd >}} -->
</section>
<section id="class-activity-simulate-an-exponential-trend-with-a-seasonal-component-15-min" class="level2">
<h2 class="anchored" data-anchor-id="class-activity-simulate-an-exponential-trend-with-a-seasonal-component-15-min">Class Activity: Simulate an Exponential Trend with a Seasonal Component (15 min)</h2>
<p>We will simulate code that has a seasonal component and impose an exponential trend.</p>
<p><a href="#fig-simTSplot">Figure&nbsp;1</a> shows the simulated time series and the time series after the natural logarithm is applied.</p>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>n_years <span class="ot">&lt;-</span> <span class="dv">9</span> <span class="co"># Number of years to simulate</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>n_months <span class="ot">&lt;-</span> n_years <span class="sc">*</span> <span class="dv">12</span> <span class="co"># Number of months</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> .<span class="dv">05</span> <span class="co"># Standard deviation of random term</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>z_t <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n_months, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> sigma)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>dates_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">floor_date</span>(<span class="fu">now</span>(), <span class="at">unit =</span> <span class="st">"year"</span>), <span class="at">length.out=</span>n_months <span class="sc">+</span> <span class="dv">1</span>, <span class="at">by=</span><span class="st">"-1 month"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">floor_date</span>(<span class="at">unit =</span> <span class="st">"month"</span>) <span class="sc">|&gt;</span> <span class="fu">sort</span>() <span class="sc">|&gt;</span> <span class="fu">head</span>(n_months)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>sim_ts <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">t =</span> <span class="dv">1</span><span class="sc">:</span>n_months,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">dates =</span> dates_seq,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="fu">arima.sim</span>(<span class="at">model=</span><span class="fu">list</span>(<span class="at">ar=</span><span class="fu">c</span>(.<span class="dv">5</span>,<span class="fl">0.2</span>)), <span class="at">n =</span> n_months, <span class="at">sd =</span> <span class="fl">0.02</span>),</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_t =</span> <span class="fu">exp</span>(<span class="dv">2</span> <span class="sc">+</span> <span class="fl">0.015</span> <span class="sc">*</span> t <span class="sc">+</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>      <span class="fl">0.03</span> <span class="sc">*</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">1</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>) <span class="sc">+</span> <span class="fl">0.04</span> <span class="sc">*</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">1</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>) <span class="sc">+</span> </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>      <span class="fl">0.05</span> <span class="sc">*</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">2</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>) <span class="sc">+</span> <span class="fl">0.03</span> <span class="sc">*</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">2</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>      <span class="fl">0.01</span> <span class="sc">*</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">3</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>) <span class="sc">+</span> <span class="fl">0.005</span> <span class="sc">*</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">3</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>      random</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">cos1 =</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">1</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">cos2 =</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">2</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">cos3 =</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">3</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">cos4 =</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">4</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">cos5 =</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">5</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">cos6 =</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">6</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">sin1 =</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">1</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">sin2 =</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">2</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">sin3 =</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">3</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">sin4 =</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">4</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">sin5 =</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">5</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>),</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">sin6 =</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> <span class="dv">6</span> <span class="sc">*</span> t <span class="sc">/</span> <span class="dv">12</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">std_t =</span> (t <span class="sc">-</span> <span class="fu">mean</span>(t)) <span class="sc">/</span> <span class="fu">sd</span>(t)) <span class="sc">|&gt;</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tsibble</span>(<span class="at">index =</span> dates)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>plot_raw <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    <span class="fu">autoplot</span>(<span class="at">.vars =</span> x_t) <span class="sc">+</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"x_t"</span>,</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>      <span class="at">title =</span> <span class="st">"Simulated Time Series"</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>plot_log <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>    <span class="fu">autoplot</span>(<span class="at">.vars =</span> <span class="fu">log</span>(x_t)) <span class="sc">+</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"log(x_t)"</span>,</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>      <span class="at">title =</span> <span class="st">"Logarithm of Simulated Time Series"</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>plot_raw <span class="sc">|</span> plot_log</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="fig-simTSplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="chapter_5_lesson_4_files/figure-html/fig-simTSplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Time plot of the time series (left) and the natural logarithm of the time series (right)</figcaption>
</figure>
</div>
<p>We will compute the (natural) logarithm of the time series values before fitting any linear models. So, our response variable will be <span class="math inline">\(\log(x_t)\)</span>, rather than <span class="math inline">\(x_t\)</span>.</p>
<p>Even though there is no visual evidence of curvature in the trend for the logarithm of the time series, we will start by fitting a model that allows for a cubic trend. (In practice, we would probably not fit this model. However, there are some things that will occur that are helpful to understand the underlying process.)</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Cubic Model">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cubic Model
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<!-- Begin hiding code for cubic model -->
<section id="cubic-model" class="level4">
<h4 class="anchored" data-anchor-id="cubic-model">Cubic Model</h4>
<p>After taking the (natural) logarithm of <span class="math inline">\(x_t\)</span>, we fit a cubic model to the log-transformed time series.</p>
<section id="full-cubic-model" class="level5">
<h5 class="anchored" data-anchor-id="full-cubic-model">Full Cubic Model</h5>
<p><span class="math display">\[\begin{align*}
  \log(x_t) &amp;= \beta_0
            + \beta_1 \left( \frac{t - \mu_t}{\sigma_t} \right)
            + \beta_2 \left( \frac{t - \mu_t}{\sigma_t} \right)^2
            + \beta_3 \left( \frac{t - \mu_t}{\sigma_t} \right)^3 \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_4 \sin \left( \frac{2\pi \cdot 1 t}{12} \right)
            + \beta_5 \cos \left( \frac{2\pi \cdot 1 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_6 \sin \left( \frac{2\pi \cdot 2 t}{12} \right)
            + \beta_7 \cos \left( \frac{2\pi \cdot 2 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_8 \sin \left( \frac{2\pi \cdot 3 t}{12} \right)
            + \beta_9 \cos \left( \frac{2\pi \cdot 3 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_{10} \sin \left( \frac{2\pi \cdot 4 t}{12} \right)
            + \beta_{11} \cos \left( \frac{2\pi \cdot 4 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_{12} \sin \left( \frac{2\pi \cdot 5 t}{12} \right)
            + \beta_{13} \cos \left( \frac{2\pi \cdot 5 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_{14} \cos \left( \frac{2\pi \cdot 6 t}{12} \right)
               \phantom{+ \beta_{15} \sin \left( \frac{2\pi \cdot 6 t}{12} \right)}
      + z_t
\end{align*}\]</span></p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cubic model with standardized time variable</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>full_cubic_lm <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">full_cubic =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3 </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="sc">+</span> sin4 <span class="sc">+</span> cos4 <span class="sc">+</span> sin5 <span class="sc">+</span> cos5 <span class="sc">+</span> cos6 )) <span class="co"># Note sin6 is omitted</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>full_cubic_lm <span class="sc">|&gt;</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sig =</span> p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 7
   .model     term         estimate std.error statistic   p.value sig  
   &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
 1 full_cubic (Intercept)  2.82       0.00327   865.    2.08e-183 TRUE 
 2 full_cubic std_t        0.473      0.00550    86.0   1.90e- 90 TRUE 
 3 full_cubic I(std_t^2)  -0.00488    0.00246    -1.98  5.02e-  2 FALSE
 4 full_cubic I(std_t^3)   0.000860   0.00285     0.302 7.64e-  1 FALSE
 5 full_cubic sin1         0.0328     0.00312    10.5   1.68e- 17 TRUE 
 6 full_cubic cos1         0.0389     0.00308    12.6   7.52e- 22 TRUE 
 7 full_cubic sin2         0.0496     0.00309    16.1   1.33e- 28 TRUE 
 8 full_cubic cos2         0.0297     0.00308     9.65  1.10e- 15 TRUE 
 9 full_cubic sin3         0.0111     0.00308     3.60  5.15e-  4 TRUE 
10 full_cubic cos3         0.00765    0.00308     2.48  1.49e-  2 TRUE 
11 full_cubic sin4         0.00155    0.00308     0.504 6.15e-  1 FALSE
12 full_cubic cos4         0.00185    0.00308     0.600 5.50e-  1 FALSE
13 full_cubic sin5         0.00169    0.00308     0.550 5.84e-  1 FALSE
14 full_cubic cos5         0.00186    0.00308     0.602 5.48e-  1 FALSE
15 full_cubic cos6         0.00184    0.00218     0.845 4.00e-  1 FALSE</code></pre>
</div>
</div>
<p>Note that neither the quadratic nor the cubic terms are statistically significant in this model. We will eliminate the cubic term and fit a model with a quadratic trend.</p>
</section>
</section>
</div>
</div>
</div>
<!-- End of cubic model -->
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Quadratic Model">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quadratic Model
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<!-- Begin hiding code for quadratic model -->
<section id="quadratic-model" class="level4">
<h4 class="anchored" data-anchor-id="quadratic-model">Quadratic Model</h4>
<p>We now fit a quadratic model to the log-transformed time series.</p>
<section id="full-quadratic-model" class="level5">
<h5 class="anchored" data-anchor-id="full-quadratic-model">Full Quadratic Model</h5>
<p>The full model with a quadratic trend is written as:</p>
<p><span class="math display">\[\begin{align*}
  \log(x_t) &amp;= \beta_0
            + \beta_1 \left( \frac{t - \mu_t}{\sigma_t} \right)
            + \beta_2 \left( \frac{t - \mu_t}{\sigma_t} \right)^2 \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_3 \sin \left( \frac{2\pi \cdot 1 t}{12} \right)
            + \beta_4 \cos \left( \frac{2\pi \cdot 1 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_5 \sin \left( \frac{2\pi \cdot 2 t}{12} \right)
            + \beta_6 \cos \left( \frac{2\pi \cdot 2 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_7 \sin \left( \frac{2\pi \cdot 3 t}{12} \right)
            + \beta_8 \cos \left( \frac{2\pi \cdot 3 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_9 \sin \left( \frac{2\pi \cdot 4 t}{12} \right)
            + \beta_{10} \cos \left( \frac{2\pi \cdot 4 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_{11} \sin \left( \frac{2\pi \cdot 5 t}{12} \right)
            + \beta_{12} \cos \left( \frac{2\pi \cdot 5 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_{13} \cos \left( \frac{2\pi \cdot 6 t}{12} \right)
               \phantom{+ \beta_{14} \sin \left( \frac{2\pi \cdot 6 t}{12} \right)}
      + z_t
\end{align*}\]</span></p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>full_quad_lm <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">full_quad =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3 </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">+</span> sin4 <span class="sc">+</span> cos4 <span class="sc">+</span> sin5 <span class="sc">+</span> cos5 <span class="sc">+</span> cos6 )) <span class="co"># Note sin6 is omitted</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>full_quad_lm <span class="sc">|&gt;</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sig =</span> p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 7
   .model    term        estimate std.error statistic   p.value sig  
   &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
 1 full_quad (Intercept)  2.82      0.00325   869.    2.41e-185 TRUE 
 2 full_quad std_t        0.475     0.00219   217.    1.02e-128 TRUE 
 3 full_quad I(std_t^2)  -0.00488   0.00244    -1.99  4.90e-  2 TRUE 
 4 full_quad sin1         0.0326    0.00307    10.6   9.09e- 18 TRUE 
 5 full_quad cos1         0.0389    0.00306    12.7   4.29e- 22 TRUE 
 6 full_quad sin2         0.0496    0.00307    16.2   6.71e- 29 TRUE 
 7 full_quad cos2         0.0298    0.00306     9.72  7.30e- 16 TRUE 
 8 full_quad sin3         0.0111    0.00306     3.61  4.97e-  4 TRUE 
 9 full_quad cos3         0.00768   0.00306     2.51  1.39e-  2 TRUE 
10 full_quad sin4         0.00153   0.00306     0.500 6.18e-  1 FALSE
11 full_quad cos4         0.00188   0.00306     0.614 5.41e-  1 FALSE
12 full_quad sin5         0.00168   0.00306     0.550 5.84e-  1 FALSE
13 full_quad cos5         0.00189   0.00306     0.616 5.39e-  1 FALSE
14 full_quad cos6         0.00186   0.00217     0.857 3.93e-  1 FALSE</code></pre>
</div>
</div>
<p>Now, note that the quadratic term is statistically significant. It was not significant when the cubic term was included in the model, but it is now.</p>
</section>
<section id="reduced-quadratic-trend-model-1" class="level5">
<h5 class="anchored" data-anchor-id="reduced-quadratic-trend-model-1">Reduced Quadratic Trend: Model 1</h5>
<p>This model omits all the Fourier (sine and cosine) terms that are not significant in the previous model.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>reduced_quadratic_lm1 <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">reduced_quadratic1 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>reduced_quadratic_lm1 <span class="sc">|&gt;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sig =</span> p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 7
  .model             term        estimate std.error statistic   p.value sig  
  &lt;chr&gt;              &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
1 reduced_quadratic1 (Intercept)  2.82      0.00320    882.   1.18e-194 TRUE 
2 reduced_quadratic1 std_t        0.475     0.00216    220.   4.66e-135 TRUE 
3 reduced_quadratic1 I(std_t^2)  -0.00487   0.00241     -2.02 4.57e-  2 TRUE 
4 reduced_quadratic1 sin1         0.0326    0.00303     10.8  2.18e- 18 TRUE 
5 reduced_quadratic1 cos1         0.0389    0.00302     12.9  6.79e- 23 TRUE 
6 reduced_quadratic1 sin2         0.0496    0.00302     16.4  5.12e- 30 TRUE 
7 reduced_quadratic1 cos2         0.0298    0.00302      9.87 2.15e- 16 TRUE 
8 reduced_quadratic1 sin3         0.0111    0.00302      3.66 4.02e-  4 TRUE 
9 reduced_quadratic1 cos3         0.00768   0.00302      2.54 1.25e-  2 TRUE </code></pre>
</div>
</div>
<p>All the terms are statistically significant in this model.</p>
</section>
<section id="reduced-quadratic-trend-model-2" class="level5">
<h5 class="anchored" data-anchor-id="reduced-quadratic-trend-model-2">Reduced Quadratic Trend: Model 2</h5>
<p>This model only includes the Fourier series terms where <span class="math inline">\(i=1\)</span> or <span class="math inline">\(i=2\)</span>.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>reduced_quadratic_lm2 <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">reduced_quadratic2 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>reduced_quadratic_lm2 <span class="sc">|&gt;</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sig =</span> p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 7
  .model             term        estimate std.error statistic   p.value sig  
  &lt;chr&gt;              &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
1 reduced_quadratic2 (Intercept)  2.82      0.00347    813.   1.54e-194 TRUE 
2 reduced_quadratic2 std_t        0.475     0.00234    203.   9.18e-134 TRUE 
3 reduced_quadratic2 I(std_t^2)  -0.00486   0.00261     -1.86 6.57e-  2 FALSE
4 reduced_quadratic2 sin1         0.0326    0.00329      9.93 1.25e- 16 TRUE 
5 reduced_quadratic2 cos1         0.0389    0.00327     11.9  6.98e- 21 TRUE 
6 reduced_quadratic2 sin2         0.0496    0.00328     15.1  1.03e- 27 TRUE 
7 reduced_quadratic2 cos2         0.0298    0.00327      9.09 8.89e- 15 TRUE </code></pre>
</div>
</div>
<p>As we would expect, all the terms are statistically significant. (They were all significant in the previous model, so it is not surprising that they are still significant.)</p>
</section>
<section id="reduced-quadratic-trend-model-3" class="level5">
<h5 class="anchored" data-anchor-id="reduced-quadratic-trend-model-3">Reduced Quadratic Trend: Model 3</h5>
<p>This model is reduced to include only the Fourier series terms for <span class="math inline">\(i=1\)</span>.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>reduced_quadratic_lm3 <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">reduced_quadratic3 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    sin1 <span class="sc">+</span> cos1)) </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>reduced_quadratic_lm3 <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sig =</span> p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
  .model             term        estimate std.error statistic   p.value sig  
  &lt;chr&gt;              &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
1 reduced_quadratic3 (Intercept)  2.82      0.00695   406.    7.13e-167 TRUE 
2 reduced_quadratic3 std_t        0.474     0.00467   101.    5.16e-105 TRUE 
3 reduced_quadratic3 I(std_t^2)  -0.00475   0.00523    -0.908 3.66e-  1 FALSE
4 reduced_quadratic3 sin1         0.0325    0.00658     4.95  2.97e-  6 TRUE 
5 reduced_quadratic3 cos1         0.0389    0.00656     5.94  3.97e-  8 TRUE </code></pre>
</div>
</div>
<p>All the terms in this parsimonious model are statistically significant.</p>
</section>
</section>
</div>
</div>
</div>
<!-- End of quadratic model -->
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Linear Model">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Linear Model
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<!-- Begin hiding code for linear model -->
<section id="linear-model" class="level4">
<h4 class="anchored" data-anchor-id="linear-model">Linear Model</h4>
<p>Even though the quadratic terms were statistically significant, there is no visual indication that there is a quadratic trend in the time series after taking the logarithm. Hence, we will now fit a linear model to the log-transformed time series. We want to be able to compare the fit of models with a linear trend to the models with quadratic trends.</p>
<section id="full-linear-model" class="level5">
<h5 class="anchored" data-anchor-id="full-linear-model">Full Linear Model</h5>
<p>First, we fit a full model with a linear trend. We can express this model as:</p>
<p><span class="math display">\[\begin{align*}
  \log(x_t) &amp;= \beta_0
            + \beta_1 \left( \frac{t - \mu_t}{\sigma_t} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_2 \sin \left( \frac{2\pi \cdot 1 t}{12} \right)
            + \beta_3 \cos \left( \frac{2\pi \cdot 1 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_4 \sin \left( \frac{2\pi \cdot 2 t}{12} \right)
            + \beta_5 \cos \left( \frac{2\pi \cdot 2 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_6 \sin \left( \frac{2\pi \cdot 3 t}{12} \right)
            + \beta_7 \cos \left( \frac{2\pi \cdot 3 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_8 \sin \left( \frac{2\pi \cdot 4 t}{12} \right)
            + \beta_9 \cos \left( \frac{2\pi \cdot 4 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_{10} \sin \left( \frac{2\pi \cdot 5 t}{12} \right)
            + \beta_{11} \cos \left( \frac{2\pi \cdot 5 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_{12} \cos \left( \frac{2\pi \cdot 6 t}{12} \right)
               \phantom{+ \beta_{13} \sin \left( \frac{2\pi \cdot 6 t}{12} \right)}
      + z_t
\end{align*}\]</span></p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>full_linear_lm <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">full_linear =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3 </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">+</span> sin4 <span class="sc">+</span> cos4 <span class="sc">+</span> sin5 <span class="sc">+</span> cos5 <span class="sc">+</span> cos6 )) <span class="co"># Note sin6 is omitted</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>full_linear_lm <span class="sc">|&gt;</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sig =</span> p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 7
   .model      term        estimate std.error statistic   p.value sig  
   &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
 1 full_linear (Intercept)  2.82      0.00220  1281.    4.18e-203 TRUE 
 2 full_linear std_t        0.475     0.00222   214.    3.22e-129 TRUE 
 3 full_linear sin1         0.0326    0.00312    10.4   1.83e- 17 TRUE 
 4 full_linear cos1         0.0388    0.00311    12.5   9.93e- 22 TRUE 
 5 full_linear sin2         0.0496    0.00311    15.9   1.47e- 28 TRUE 
 6 full_linear cos2         0.0298    0.00311     9.56  1.41e- 15 TRUE 
 7 full_linear sin3         0.0110    0.00311     3.55  5.99e-  4 TRUE 
 8 full_linear cos3         0.00767   0.00311     2.47  1.54e-  2 TRUE 
 9 full_linear sin4         0.00153   0.00311     0.492 6.24e-  1 FALSE
10 full_linear cos4         0.00188   0.00311     0.604 5.47e-  1 FALSE
11 full_linear sin5         0.00168   0.00311     0.541 5.90e-  1 FALSE
12 full_linear cos5         0.00189   0.00311     0.607 5.45e-  1 FALSE
13 full_linear cos6         0.00186   0.00220     0.844 4.01e-  1 FALSE</code></pre>
</div>
</div>
</section>
<section id="reduced-linear-trend-model-1" class="level5">
<h5 class="anchored" data-anchor-id="reduced-linear-trend-model-1">Reduced Linear Trend: Model 1</h5>
<p>This model excludes the terms that were not significant in the full model with a linear trend.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>reduced_linear_lm1 <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">reduced_linear1 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>reduced_linear_lm1 <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sig =</span> p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 7
  .model          term        estimate std.error statistic   p.value sig  
  &lt;chr&gt;           &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
1 reduced_linear1 (Intercept)  2.82      0.00217   1301.   2.91e-213 TRUE 
2 reduced_linear1 std_t        0.475     0.00219    217.   1.58e-135 TRUE 
3 reduced_linear1 sin1         0.0326    0.00307     10.6  4.53e- 18 TRUE 
4 reduced_linear1 cos1         0.0388    0.00306     12.7  1.63e- 22 TRUE 
5 reduced_linear1 sin2         0.0496    0.00307     16.2  1.18e- 29 TRUE 
6 reduced_linear1 cos2         0.0298    0.00306      9.71 4.25e- 16 TRUE 
7 reduced_linear1 sin3         0.0111    0.00306      3.61 4.86e-  4 TRUE 
8 reduced_linear1 cos3         0.00767   0.00306      2.50 1.39e-  2 TRUE </code></pre>
</div>
</div>
<p>All of the terms are significant in this model.</p>
</section>
<section id="reduced-linear-trend-model-2" class="level5">
<h5 class="anchored" data-anchor-id="reduced-linear-trend-model-2">Reduced Linear Trend: Model 2</h5>
<p>We reduce the model to see if a more parsimonious model will suffice. This model contains a linear trend and the Fourier series terms associated with <span class="math inline">\(i=1\)</span> and <span class="math inline">\(i=2\)</span>.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>reduced_linear_lm2 <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">reduced_linear2 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>reduced_linear_lm2 <span class="sc">|&gt;</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sig =</span> p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  .model          term        estimate std.error statistic   p.value sig  
  &lt;chr&gt;           &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
1 reduced_linear2 (Intercept)   2.82     0.00234   1203.   1.37e-213 TRUE 
2 reduced_linear2 std_t         0.475    0.00237    201.   2.51e-134 TRUE 
3 reduced_linear2 sin1          0.0326   0.00332      9.81 2.14e- 16 TRUE 
4 reduced_linear2 cos1          0.0388   0.00331     11.7  1.35e- 20 TRUE 
5 reduced_linear2 sin2          0.0496   0.00332     14.9  1.88e- 27 TRUE 
6 reduced_linear2 cos2          0.0298   0.00331      8.98 1.46e- 14 TRUE </code></pre>
</div>
</div>
<p>All the terms in this model are statistically significant.</p>
</section>
<section id="reduced-linear-trend-model-3" class="level5">
<h5 class="anchored" data-anchor-id="reduced-linear-trend-model-3">Reduced Linear Trend: Model 3</h5>
<p>Finally, we fit a more reduced model that includes a linear trend and only the Fourier terms associated with <span class="math inline">\(i=1\)</span>.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>reduced_linear_lm3 <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">reduced_linear3 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    sin1 <span class="sc">+</span> cos1)) </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>reduced_linear_lm3 <span class="sc">|&gt;</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sig =</span> p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  .model          term        estimate std.error statistic   p.value sig  
  &lt;chr&gt;           &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
1 reduced_linear3 (Intercept)   2.82     0.00463    609.   1.56e-186 TRUE 
2 reduced_linear3 std_t         0.474    0.00467    101.   7.71e-106 TRUE 
3 reduced_linear3 sin1          0.0325   0.00657      4.95 2.92e-  6 TRUE 
4 reduced_linear3 cos1          0.0389   0.00655      5.93 3.98e-  8 TRUE </code></pre>
</div>
</div>
<p>Each of these terms is significant.</p>
</section>
</section>
</div>
</div>
</div>
<!-- End of linear model -->
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Model Comparison">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Comparison
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<!-- Begin hiding code for model comparison -->
<section id="comparison-of-fitted-models" class="level4">
<h4 class="anchored" data-anchor-id="comparison-of-fitted-models">Comparison of Fitted Models</h4>
<section id="aic-aicc-and-bic" class="level5">
<h5 class="anchored" data-anchor-id="aic-aicc-and-bic">AIC, AICc, and BIC</h5>
<p>We will now compare the models we fitted above. #tbl-ModelComparison gives the AIC, AICc, and BIC of the models fitted above.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>model_combined <span class="ot">&lt;-</span> sim_ts <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">full_cubic =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                    sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3 </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span> sin4 <span class="sc">+</span> cos4 <span class="sc">+</span> sin5 <span class="sc">+</span> cos5 <span class="sc">+</span> cos6 ),</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">full_quad =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>                       sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3 </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">+</span> sin4 <span class="sc">+</span> cos4 <span class="sc">+</span> sin5 <span class="sc">+</span> cos5 <span class="sc">+</span> cos6 ),</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">reduced_quadratic1 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">reduced_quadratic2 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2),</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">reduced_quadratic3 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> sin1 <span class="sc">+</span> cos1),</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">full_linear =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> </span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                         sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3 </span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>                       <span class="sc">+</span> sin4 <span class="sc">+</span> cos4 <span class="sc">+</span> sin5 <span class="sc">+</span> cos5 <span class="sc">+</span> cos6 ),</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">reduced_linear1 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3),</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">reduced_linear2 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2),</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">reduced_linear3 =</span> <span class="fu">TSLM</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> sin1 <span class="sc">+</span> cos1) </span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_combined) <span class="sc">|&gt;</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.model, AIC, AICc, BIC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ModelComparison" class="anchored">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>Table&nbsp;1: Comparison of the AIC, AICc, and BIC values for the models fitted to the logarithm of the simulated time series.</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Model</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">AICc</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; min-width: 0in;">full_cubic</td>
<td style="text-align: center; min-width: 0in;">-802.6</td>
<td style="text-align: center; min-width: 0in;">-796.6</td>
<td style="text-align: center; min-width: 0in;">-759.6</td>
</tr>
<tr class="even">
<td style="text-align: center; min-width: 0in;">full_quad</td>
<td style="text-align: center; min-width: 0in;">-804.5</td>
<td style="text-align: center; min-width: 0in;">-799.2</td>
<td style="text-align: center; min-width: 0in;">-764.2</td>
</tr>
<tr class="odd">
<td style="text-align: center; min-width: 0in;">reduced_quadratic1</td>
<td style="text-align: center; min-width: 0in;">**-812.1**</td>
<td style="text-align: center; min-width: 0in;">**-809.9**</td>
<td style="text-align: center; min-width: 0in;">-785.3</td>
</tr>
<tr class="even">
<td style="text-align: center; min-width: 0in;">reduced_quadratic2</td>
<td style="text-align: center; min-width: 0in;">-796.3</td>
<td style="text-align: center; min-width: 0in;">-794.9</td>
<td style="text-align: center; min-width: 0in;">-774.9</td>
</tr>
<tr class="odd">
<td style="text-align: center; min-width: 0in;">reduced_quadratic3</td>
<td style="text-align: center; min-width: 0in;">-648.3</td>
<td style="text-align: center; min-width: 0in;">-647.4</td>
<td style="text-align: center; min-width: 0in;">-632.2</td>
</tr>
<tr class="even">
<td style="text-align: center; min-width: 0in;">full_linear</td>
<td style="text-align: center; min-width: 0in;">-802</td>
<td style="text-align: center; min-width: 0in;">-797.5</td>
<td style="text-align: center; min-width: 0in;">-764.4</td>
</tr>
<tr class="odd">
<td style="text-align: center; min-width: 0in;">reduced_linear1</td>
<td style="text-align: center; min-width: 0in;">-809.8</td>
<td style="text-align: center; min-width: 0in;">-807.9</td>
<td style="text-align: center; min-width: 0in;">**-785.6**</td>
</tr>
<tr class="even">
<td style="text-align: center; min-width: 0in;">reduced_linear2</td>
<td style="text-align: center; min-width: 0in;">-794.7</td>
<td style="text-align: center; min-width: 0in;">-793.6</td>
<td style="text-align: center; min-width: 0in;">-775.9</td>
</tr>
<tr class="odd">
<td style="text-align: center; min-width: 0in;">reduced_linear3</td>
<td style="text-align: center; min-width: 0in;">-649.4</td>
<td style="text-align: center; min-width: 0in;">-648.8</td>
<td style="text-align: center; min-width: 0in;">-636</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>The model with the lowest AIC and AICc values is the reduced quadratic trend model 1. This can be written as:</p>
<p><span class="math display">\[\begin{align*}
  \log(x_t) &amp;= \beta_0
            + \beta_1 \left( \frac{t - \mu_t}{\sigma_t} \right)
            + \beta_2 \left( \frac{t - \mu_t}{\sigma_t} \right)^2 \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_3 \sin \left( \frac{2\pi \cdot 1 t}{12} \right)
            + \beta_4 \cos \left( \frac{2\pi \cdot 1 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_5 \sin \left( \frac{2\pi \cdot 2 t}{12} \right)
            + \beta_6 \cos \left( \frac{2\pi \cdot 2 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_7 \sin \left( \frac{2\pi \cdot 3 t}{12} \right)
            + \beta_8 \cos \left( \frac{2\pi \cdot 3 t}{12} \right)
      + z_t
\end{align*}\]</span></p>
<p>The model with the lowest BIC is the reduced linear trend model 1. We express this model as:</p>
<p><span class="math display">\[\begin{align*}
  \log(x_t) &amp;= \beta_0
            + \beta_1 \left( \frac{t - \mu_t}{\sigma_t} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_2 \sin \left( \frac{2\pi \cdot 1 t}{12} \right)
            + \beta_3 \cos \left( \frac{2\pi \cdot 1 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_4 \sin \left( \frac{2\pi \cdot 2 t}{12} \right)
            + \beta_5 \cos \left( \frac{2\pi \cdot 2 t}{12} \right) \\
      &amp; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + \beta_6 \sin \left( \frac{2\pi \cdot 3 t}{12} \right)
            + \beta_7 \cos \left( \frac{2\pi \cdot 3 t}{12} \right)
      + z_t
\end{align*}\]</span></p>
<p>Both of these models have very low AIC, AICc, and BIC values.</p>
<p>We will take a deeper look at the residuals of these two models to assess if there is evidence of autocorrelation in the random terms. We compute the autocorrelation function and the partial autocorrelation function of the residuals for both. If there is evidence of autocorrelation, we will use the GLS algorithm to fit the models, since it will take into account the autocorrelation in the terms.</p>
</section>
</section>
</div>
</div>
</div>
<!-- End of model comparison -->
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Autocorrelation of the Random Component">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Autocorrelation of the Random Component
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<!-- Begin hiding code for checking autocorrelation of the random component -->
<section id="investigating-autocorrelation-of-the-random-component" class="level4">
<h4 class="anchored" data-anchor-id="investigating-autocorrelation-of-the-random-component">Investigating Autocorrelation of the Random Component</h4>
<p>Recall that if there is autocorrelation in the random component, the standard error of the parameter estimates tends to be underestimated. We can account for this autocorrelation using Generalized Least Squares, GLS, if needed.</p>
<section id="reduced-quadratic-trend-model-1-1" class="level5">
<h5 class="anchored" data-anchor-id="reduced-quadratic-trend-model-1-1">Reduced Quadratic Trend: Model 1</h5>
<p><a href="#fig-QuadACF">Figure&nbsp;2</a> illustrates the ACF of the reduced model 1 with quadratic trend.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>resid_q1_ts <span class="ot">&lt;-</span> reduced_quadratic_lm1 <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">residuals</span>() </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(resid_q1_ts<span class="sc">$</span>.resid, <span class="at">plot=</span><span class="cn">TRUE</span>, <span class="at">lag.max =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-QuadACF" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="chapter_5_lesson_4_files/figure-html/fig-QuadACF-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;2: ACF of reduced model 1 with a quadratic trend</figcaption>
</figure>
</div>
</div>
</div>
<p>Notice that the residual correlogram indicates a positive autocorrelation in the values. This suggests that the standard errors of the regression coefficients will be underestimated, which means that some predictors can appear to be statistically significant when they are not.</p>
<p><a href="#fig-QuadPACF">Figure&nbsp;3</a> illustrates the PACF of the reduced model 1 with quadratic trend.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(resid_q1_ts<span class="sc">$</span>.resid, <span class="at">plot=</span><span class="cn">TRUE</span>, <span class="at">lag.max =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-QuadPACF" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="chapter_5_lesson_4_files/figure-html/fig-QuadPACF-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;3: PACF of reduced model 1 with a quadratic trend</figcaption>
</figure>
</div>
</div>
</div>
<p>Only the first partial autocorrelation is statistically significant. The partial autocorrelation plot indicates that an <span class="math inline">\(AR(1)\)</span> model could adequately model the random component of the logarithm of the time series. Recall that in <a href="https://byuistats.github.io/timeseries/chapter_5_lesson_1.html#FittingRegModelWithPACF">Chapter 5, Lesson 1</a>, we fitted a linear regression model using the value of the partial autocorrelation function for <span class="math inline">\(k=1\)</span>. This helps account for the autocorrelation in the residuals.</p>
<p>The first few partial autocorrelation values are:</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(resid_q1_ts<span class="sc">$</span>.resid, <span class="at">plot=</span><span class="cn">FALSE</span>, <span class="at">lag.max =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Partial autocorrelations of series 'resid_q1_ts$.resid', by lag

     1      2      3      4      5      6      7      8      9     10 
 0.479  0.091 -0.004 -0.101 -0.018 -0.129 -0.051  0.016  0.037  0.069 </code></pre>
</div>
</div>
<p>The partial autocorrelation when <span class="math inline">\(k=1\)</span> is approximately 0.479. We will use this value as we recompute the regression coefficients.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load additional packages</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidymodels, multilevelmod,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  nlme, broom.mixed)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>temp_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"gls"</span>, <span class="at">correlation =</span> nlme<span class="sc">::</span><span class="fu">corAR1</span>(<span class="fl">0.479</span>))</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>temp_gls <span class="ot">&lt;-</span> temp_spec <span class="sc">|&gt;</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> <span class="fu">I</span>(std_t<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3, <span class="at">data =</span> sim_ts)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(temp_gls) <span class="sc">|&gt;</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> estimate <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.025</span>) <span class="sc">*</span> std.error,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> estimate <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">*</span> std.error</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 7
  term        estimate std.error statistic   p.value    lower   upper
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)  2.82      0.00590    479.   2.33e-168  2.81    2.84   
2 std_t        0.475     0.00389    122.   9.61e-110  0.467   0.482  
3 I(std_t^2)  -0.00497   0.00427     -1.16 2.48e-  1 -0.0133  0.00341
4 sin1         0.0325    0.00442      7.36 5.38e- 11  0.0239  0.0412 
5 cos1         0.0389    0.00436      8.92 2.45e- 14  0.0303  0.0474 
6 sin2         0.0495    0.00307     16.1  1.99e- 29  0.0435  0.0555 
7 cos2         0.0298    0.00306      9.75 3.77e- 16  0.0238  0.0358 
8 sin3         0.0110    0.00235      4.68 9.18e-  6  0.00639 0.0156 
9 cos3         0.00773   0.00235      3.29 1.40e-  3  0.00312 0.0123 </code></pre>
</div>
</div>
<p>The quadratic term is not statistically significant in this model! After accounting for the autocorrelation in the random component, the quadratic component of the trend is not statistically significant. This is a great example of an instance where ordinary linear regression leads to errant results.</p>
<p>We now consider the reduced model 1 where the trend is linear.</p>
</section>
<section id="reduced-linear-trend-model-1-1" class="level5">
<h5 class="anchored" data-anchor-id="reduced-linear-trend-model-1-1">Reduced Linear Trend: Model 1</h5>
<p><a href="#fig-LinearACF">Figure&nbsp;4</a> illustrates the ACF of the reduced model 1 with linear trend.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>resid_lin1_ts <span class="ot">&lt;-</span> reduced_linear_lm1 <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">residuals</span>() </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(resid_lin1_ts<span class="sc">$</span>.resid, <span class="at">plot=</span><span class="cn">TRUE</span>, <span class="at">lag.max =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-LinearACF" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="chapter_5_lesson_4_files/figure-html/fig-LinearACF-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;4: ACF of reduced model 1 with a linear trend</figcaption>
</figure>
</div>
</div>
</div>
<p>We observe evidence of autocorrelation in the random terms.</p>
<p><a href="#fig-LinearPACF">Figure&nbsp;5</a> illustrates the PACF of the reduced model 1 with linear trend.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>alphas_lin <span class="ot">&lt;-</span> <span class="fu">pacf</span>(resid_lin1_ts<span class="sc">$</span>.resid, <span class="at">plot=</span><span class="cn">FALSE</span>, <span class="at">lag.max =</span> <span class="dv">25</span>) </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(resid_lin1_ts<span class="sc">$</span>.resid, <span class="at">plot=</span><span class="cn">TRUE</span>, <span class="at">lag.max =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-LinearPACF" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="chapter_5_lesson_4_files/figure-html/fig-LinearPACF-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;5: ACF of reduced model 1 with a linear trend</figcaption>
</figure>
</div>
</div>
</div>
<p>We will use the PACF when <span class="math inline">\(k=1\)</span> to apply the GLS algorithm. The first few partial autocorrelation values are:</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(resid_lin1_ts<span class="sc">$</span>.resid, <span class="at">plot=</span><span class="cn">FALSE</span>, <span class="at">lag.max =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Partial autocorrelations of series 'resid_lin1_ts$.resid', by lag

     1      2      3      4      5      6      7      8      9     10 
 0.497  0.122  0.017 -0.088  0.006 -0.100 -0.018  0.042  0.060  0.087 </code></pre>
</div>
</div>
<p>The partial autocorrelation when <span class="math inline">\(k=1\)</span> is approximately 0.497. We will use this value as we recompute the regression coefficients.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load additional packages</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidymodels, multilevelmod,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  nlme, broom.mixed)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>temp_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"gls"</span>, <span class="at">correlation =</span> nlme<span class="sc">::</span><span class="fu">corAR1</span>(<span class="fl">0.497</span>))</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>temp_gls <span class="ot">&lt;-</span> temp_spec <span class="sc">|&gt;</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="fu">log</span>(x_t) <span class="sc">~</span> std_t <span class="sc">+</span> sin1 <span class="sc">+</span> cos1 <span class="sc">+</span> sin2 <span class="sc">+</span> cos2 <span class="sc">+</span> sin3 <span class="sc">+</span> cos3, <span class="at">data =</span> sim_ts)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(temp_gls) <span class="sc">|&gt;</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> estimate <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.025</span>) <span class="sc">*</span> std.error,</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> estimate <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">*</span> std.error</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 7
  term        estimate std.error statistic   p.value   lower  upper
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
1 (Intercept)  2.82      0.00398    708.   8.15e-187 2.81    2.83  
2 std_t        0.475     0.00393    121.   3.80e-110 0.467   0.482 
3 sin1         0.0324    0.00444      7.30 6.96e- 11 0.0237  0.0412
4 cos1         0.0386    0.00438      8.82 3.85e- 14 0.0300  0.0472
5 sin2         0.0494    0.00308     16.1  1.83e- 29 0.0434  0.0555
6 cos2         0.0297    0.00306      9.71 4.31e- 16 0.0237  0.0357
7 sin3         0.0110    0.00235      4.66 9.69e-  6 0.00635 0.0156
8 cos3         0.00769   0.00235      3.27 1.47e-  3 0.00308 0.0123</code></pre>
</div>
</div>
<p><a href="#fig-finalFittedPlot">Figure&nbsp;6</a> illustrates the original time series (in black) and the fitted model (in blue). For reference, a dotted line illustrating the simple least squares line is plotted on this figure for reference. It helps highlight the exponential shape of the trend.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>forecast_df <span class="ot">&lt;-</span> reduced_linear_lm1 <span class="sc">|&gt;</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">forecast</span>(sim_ts) <span class="sc">|&gt;</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(std_t, .mean) <span class="sc">|&gt;</span> </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">pred =</span> .mean)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>sim_ts <span class="sc">|&gt;</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(forecast_df, <span class="at">by =</span> <span class="st">"std_t"</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tsibble</span>(<span class="at">index =</span> dates) <span class="sc">|&gt;</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>(<span class="at">.vars =</span> x_t) <span class="sc">+</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> <span class="st">'y ~ x'</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"#E69F00"</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>) <span class="sc">+</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred), <span class="at">color =</span> <span class="st">"#56B4E9"</span>, <span class="at">alpha =</span> <span class="fl">0.75</span>) <span class="sc">+</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"Simulated Time Series"</span>,</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">title =</span> <span class="st">"Time Plot of Simulated Time Series with an Exponential Trend"</span>,</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">subtitle =</span> <span class="st">"Predicted values based on the full cubic model are given in blue"</span></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-finalFittedPlot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="chapter_5_lesson_4_files/figure-html/fig-finalFittedPlot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Time plot of the time series (left) and the natural logarithm of the time series (right)</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
</div>
</div>
</div>
<!-- End of Checking Autocorrelation of Residuals -->
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Comparison of the Fitted Coefficients to the Simulation Parameters">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Comparison of the Fitted Coefficients to the Simulation Parameters
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<!-- Begin hiding code for the comparison -->
<section id="comparison-of-model-coefficients" class="level4">
<h4 class="anchored" data-anchor-id="comparison-of-model-coefficients">Comparison of Model Coefficients</h4>
<p>Note that the mean of the <span class="math inline">\(x_t\)</span> values is <span class="math inline">\(\bar x_t = 18.699\)</span>, and the standard deviation is <span class="math inline">\(s_t = 8.691\)</span>.</p>
<p>The fitted model is: <span class="math display">\[\begin{align*}
  \hat x_t
      &amp;= e^{
          2.819
          + 0.475
                ~ \left( \frac{t - 18.699}{8.691} \right)
          + 0.032
                ~ \sin \left( \frac{2 \pi \cdot 1 t }{ 12 } \right)
          + 0.039
                ~ \cos \left( \frac{2 \pi \cdot 1 t }{ 12 } \right)
          + 0.049
                ~ \sin \left( \frac{2 \pi \cdot 2 t }{ 12 } \right)
          + 0.03
                ~ \cos \left( \frac{2 \pi \cdot 2 t }{ 12 } \right)
          + 0.011
                ~ \sin \left( \frac{2 \pi \cdot 3 t }{ 12 } \right)
          + 0.008
                ~ \cos \left( \frac{2 \pi \cdot 3 t }{ 12 } \right)
     }
     \\
     &amp;= e^{
          2.819
          + 0.475
                ~ \left( \frac{t}{8.691} \right)
          - 0.475
                ~ \left( \frac{18.699}{8.691} \right)
          + 0.032
                ~ \sin \left( \frac{2 \pi \cdot 1 t }{ 12 } \right)
          + 0.039
                ~ \cos \left( \frac{2 \pi \cdot 1 t }{ 12 } \right)
          + 0.049
                ~ \sin \left( \frac{2 \pi \cdot 2 t }{ 12 } \right)
          + 0.03
                ~ \cos \left( \frac{2 \pi \cdot 2 t }{ 12 } \right)
          + 0.011
                ~ \sin \left( \frac{2 \pi \cdot 3 t }{ 12 } \right)
          + 0.008
                ~ \cos \left( \frac{2 \pi \cdot 3 t }{ 12 } \right)
     }
     \\
     &amp;= e^{
          2.819
          + 0.055 ~ t
          - 1.021
          + 0.032
                ~ \sin \left( \frac{2 \pi \cdot 1 t }{ 12 } \right)
          + 0.039
                ~ \cos \left( \frac{2 \pi \cdot 1 t }{ 12 } \right)
          + 0.049
                ~ \sin \left( \frac{2 \pi \cdot 2 t }{ 12 } \right)
          + 0.03
                ~ \cos \left( \frac{2 \pi \cdot 2 t }{ 12 } \right)
          + 0.011
                ~ \sin \left( \frac{2 \pi \cdot 3 t }{ 12 } \right)
          + 0.008
                ~ \cos \left( \frac{2 \pi \cdot 3 t }{ 12 } \right)
     }
     \\
     &amp;= e^{
          1.797
          + 0.055 ~ t
          + 0.032
                ~ \sin \left( \frac{2 \pi \cdot 1 t }{ 12 } \right)
          + 0.039
                ~ \cos \left( \frac{2 \pi \cdot 1 t }{ 12 } \right)
          + 0.049
                ~ \sin \left( \frac{2 \pi \cdot 2 t }{ 12 } \right)
          + 0.03
                ~ \cos \left( \frac{2 \pi \cdot 2 t }{ 12 } \right)
          + 0.011
                ~ \sin \left( \frac{2 \pi \cdot 3 t }{ 12 } \right)
          + 0.008
                ~ \cos \left( \frac{2 \pi \cdot 3 t }{ 12 } \right)
     }
\end{align*}\]</span></p>
<p>Notice how well this matches the original model used to simulate the data.</p>
<p><span class="math display">\[\begin{align*}
  x_t &amp;= e^{
          2 + 0.015 t +
       0.03 ~ \sin \left( \frac{2 \pi \cdot 1 t }{ 12 } \right) + 0.04 ~ \cos \left( \frac{2 \pi \cdot 1 t }{ 12 } \right) +
       0.05 ~ \sin \left( \frac{2 \pi \cdot 2 t }{ 12 } \right) + 0.03 ~ \cos \left( \frac{2 \pi \cdot 2 t }{ 12 } \right) +
       0.01 ~ \sin \left( \frac{2 \pi \cdot 3 t }{ 12 } \right) + 0.005 ~ \cos \left( \frac{2 \pi \cdot 3 t }{ 12 } \right) +
        z_t
     }
\end{align*}\]</span> where <span class="math inline">\(z_t = 0.5 z_{t-1} + 0.2 z_{t-2} + w_t\)</span> and <span class="math inline">\(w_t\)</span> is a white noise process with standard deviation of 0.02.</p>
</section>
</div>
</div>
</div>
<!-- End of the big reveal -->
</section>
<section id="small-group-activity-retail-sales-20-min" class="level2">
<h2 class="anchored" data-anchor-id="small-group-activity-retail-sales-20-min">Small-Group Activity: Retail Sales (20 min)</h2>
<p><a href="#fig-RetailSalesGeneralMerch">Figure&nbsp;7</a> gives the total sales (in millions of U.S. dollars) for the category “all other general merchandise stores (45299).”</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in retail sales data for "all other general merchandise stores"</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>retail_ts <span class="ot">&lt;-</span> rio<span class="sc">::</span><span class="fu">import</span>(<span class="st">"https://byuistats.github.io/timeseries/data/retail_by_business_type.parquet"</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(naics <span class="sc">==</span> <span class="dv">45299</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tsibble</span>(<span class="at">index =</span> month)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>retail_ts <span class="sc">|&gt;</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>(<span class="at">.vars =</span> sales_millions) <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"Sales (Millions of U.S. Dollars)"</span>,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">title =</span> <span class="fu">paste0</span>(retail_ts<span class="sc">$</span>business[<span class="dv">1</span>], <span class="st">" ("</span>, retail_ts<span class="sc">$</span>naics[<span class="dv">1</span>], <span class="st">")"</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-RetailSalesGeneralMerch" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="chapter_5_lesson_4_files/figure-html/fig-RetailSalesGeneralMerch-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;7: Time plot of the total monthly retail sales for all other general merchandise stores (45299)</figcaption>
</figure>
</div>
</div>
</div>
<!-- Check Your Understanding -->
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Check Your Understanding">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check Your Understanding
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <a href="#fig-RetailSalesGeneralMerch">Figure&nbsp;7</a> to explain the following questions to a partner.</p>
<ul>
<li>What is the shape of the trend of this time series?</li>
<li>Which decomposition would be more appropriate: additive or multiplicative? Justify your answer.</li>
<li>Apply the appropriate transformation to the time series.</li>
<li>Fit models utilizing the Fourier terms for seasonal components.</li>
<li>Determine the “best” model for these data. Justify your decision.</li>
<li>Check for autocorrelation in the random terms.</li>
<li>Use GLS to fit the model, if there is evidence of autocorrelation in the random component.</li>
<li>Refine your choice of the “best” model, if necessary. Justify your actions.</li>
<li>Plot the fitted values and the time series on the same figure.</li>
</ul>
</div>
</div>
</section>
<section id="class-activity-simulated-non-linear-series-10-min" class="level2">
<h2 class="anchored" data-anchor-id="class-activity-simulated-non-linear-series-10-min">Class Activity: Simulated Non-Linear Series (10 min)</h2>
<p>In Section 5.8 of the textbook, we are introduced to the possibility that a time series could have an exponential trend but also exhibit negative values. In this case, the logarithm of the negative values is not defined, so we need a different approach to fit the model.</p>
<p>We will fit the non-linear time series</p>
<p><span class="math display">\[
x_t = -c_0 + e^{\alpha_0 + \alpha_1 t} + z_t
\]</span></p>
<p>where the time series can assume negative values.</p>
<p>We present the simulation from the textbook here:</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">w =</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">10</span>)) <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">Time =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">n</span>(),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">z =</span> purrr<span class="sc">::</span><span class="fu">accumulate2</span>(</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">lag</span>(w), w, </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>            \(acc, nxt, w) <span class="fl">0.7</span> <span class="sc">*</span> acc <span class="sc">+</span> w,</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">.init =</span> <span class="dv">0</span>)[<span class="sc">-</span><span class="dv">1</span>],</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="fu">exp</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fl">0.05</span> <span class="sc">*</span> Time) <span class="sc">+</span> z) <span class="sc">|&gt;</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    tsibble<span class="sc">::</span><span class="fu">as_tsibble</span>(<span class="at">index =</span> Time)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(dat, <span class="at">.var =</span> x) <span class="sc">+</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Time"</span>,</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Value"</span>,</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Time Plot of Simulated Non-Linear Series"</span></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-TextbokSimulationTimePlot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="chapter_5_lesson_4_files/figure-html/fig-TextbokSimulationTimePlot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;8: Time plot of a simulated non-linear series</figcaption>
</figure>
</div>
</div>
</div>
<p>We will fit the non-linear model given above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>equation <span class="ot">&lt;-</span> x <span class="sc">~</span> <span class="fu">exp</span>(alp0 <span class="sc">+</span> alp1 <span class="sc">*</span> Time)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>dat_nls <span class="ot">&lt;-</span> <span class="fu">nls</span>(equation, <span class="at">data =</span> dat,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">start =</span> <span class="fu">list</span>(<span class="at">alp0 =</span> <span class="fl">0.1</span>, <span class="at">alp1 =</span> <span class="fl">0.5</span>))</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dat_nls)<span class="sc">$</span>parameters</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Estimate   Std. Error  t value     Pr(&gt;|t|)
alp0 1.17299000 0.0743864844 15.76886 1.232132e-28
alp1 0.04832158 0.0008197862 58.94413 2.432828e-78</code></pre>
</div>
</div>
<p>The model we fitted was</p>
<p><span class="math display">\[
  x_t = e^{1 + 0.05 t} + z_t
\]</span></p>
<p>where</p>
<p><span class="math display">\[
  z_t = 0.7 z_{t-1} + w_t
\]</span> and <span class="math inline">\(w_t\)</span> is a white noise process.</p>
<p>Our fitted model is: <span class="math display">\[
  \hat x_t = e^{1.173 + 0.048 t}
\]</span></p>
<p>Notice that our estimates are quite close to the parameters used in the simulation.</p>
<!-- Check your Understanding -->
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Check Your Understanding">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check Your Understanding
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Modify the time series and repeat the simulation.</li>
<li>Fit your model using the <code>nls</code> function in R.</li>
<li>Compare the parameter estimates with the actual values from your simulation.</li>
</ul>
</div>
</div>
</section>
<section id="homework-preview-5-min" class="level2">
<h2 class="anchored" data-anchor-id="homework-preview-5-min">Homework Preview (5 min)</h2>
<ul>
<li>Review upcoming homework assignment</li>
<li>Clarify questions</li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Download Homework
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://byuistats.github.io/timeseries/homework/homework_5_4.qmd" download="homework_5_4.qmd"> homework_5_4.qmd </a></p>
</div>
</div>
<!-- Solutions at the bottom of the page -->
<p><a href="javascript:showhide('Solutions')" style="font-size:.8em;">Small-Group Activity</a></p>
<div id="Solutions" style="display:none;">
<p>Insert code for Small-Group Activity here</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter_5_lesson_3.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Harmonic Seasonal Variables - Part 2</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter_5_lesson_5.html" class="pagination-link">
        <span class="nav-page-text">Forecasting, Inverse Transformation, and Bias Correction</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>