---
title: "Testing Code"
author: "David Pineda"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
    toc: true
    toc_float: true
---

# Description


This file is able to get the financial data from yahoo finance, then using a specific time frame, chart out the results of the growth in that stock 


# Packages

```{r, warning=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  tsibble, fable, feasts, tsibbledata,
  fable.prophet, tidyverse, patchwork, rio,
  arrow, tidyquant, lubridate, dygraphs, riem, ggplot2, scales, plotly
)
```



```{r}
# Set symbol and date range
symbol <- "NFLX"
date_start <- "2020-01-16"
date_end <- "2024-01-17"

# Fetch stock prices
df_stock <- tq_get(symbol, from = date_start, to = date_end, get = "stock.prices")
```



```{r}
# Transform data into tibble
df_tibble <- df_stock %>%
  mutate(
    dates = date, 
    year = lubridate::year(dates),
    month = lubridate::month(dates),
    value = adjusted
  ) %>%
  select(dates, year, month, value) %>%
  as_tibble() %>% 
  arrange(dates)
```



```{r}
# Convert tibble to tsibble
desired_tsibble <- as_tsibble(df_tibble, index = dates, key = NULL)

# Extract year and month from dates
desired_tsibble <- desired_tsibble %>%
  mutate(
    year = lubridate::year(dates),
    month = lubridate::month(dates)
  ) %>%
  select(-dates)
```



```{r}
# Generate time series plot using plot_ly
plot_ly(desired_tsibble, x = ~dates, y = ~value, type = 'scatter', mode = 'lines') %>%
  layout(
    xaxis = list(title = ""),
    yaxis = list(title = "Value"),
    title = "Time Series Plot"
  )
```

```{r}
plot_ly(desired_tsibble, x = ~factor(month), y = ~value, type = 'box') %>%
  layout(
    xaxis = list(title = ""),
    yaxis = list(title = "Value"),
    title = "Boxplot of Time Series Data by Month"
  )
```



```{r}
# computes the 12-month centered moving average (m_hat)
desired_tsibble <- desired_tsibble |> 
  mutate(
    m_hat = (
          (1/2) * lag(value, 6)
          + lag(value, 5)
          + lag(value, 4)
          + lag(value, 3)
          + lag(value, 2)
          + lag(value, 1)
          + value
          + lead(value, 1)
          + lead(value, 2)
          + lead(value, 3)
          + lead(value, 4)
          + lead(value, 5)
          + (1/2) * lead(value, 6)
        ) / 12
  )
desired_tsibble
```




